//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kometra.Assets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kometra.Assets.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Node.
        /// </summary>
        public static string MenuAddNode {
            get {
                return ResourceManager.GetString("MenuAddNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align and Center.
        /// </summary>
        public static string MenuAlignCenter {
            get {
                return ResourceManager.GetString("MenuAlignCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop.
        /// </summary>
        public static string MenuCrop {
            get {
                return ResourceManager.GetString("MenuCrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header Editor / Metadata.
        /// </summary>
        public static string MenuHeaderEditor {
            get {
                return ResourceManager.GetString("MenuHeaderEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear.
        /// </summary>
        public static string MenuLinear {
            get {
                return ResourceManager.GetString("MenuLinear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Contrast.
        /// </summary>
        public static string MenuLocalContrast {
            get {
                return ResourceManager.GetString("MenuLocalContrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logarithmic.
        /// </summary>
        public static string MenuLogarithmic {
            get {
                return ResourceManager.GetString("MenuLogarithmic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        public static string MenuModify {
            get {
                return ResourceManager.GetString("MenuModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morphological Analysis.
        /// </summary>
        public static string MenuMorphAnalysis {
            get {
                return ResourceManager.GetString("MenuMorphAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Astrometric Solving (ASTAP).
        /// </summary>
        public static string MenuPlateSolving {
            get {
                return ResourceManager.GetString("MenuPlateSolving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posterization.
        /// </summary>
        public static string MenuPosterization {
            get {
                return ResourceManager.GetString("MenuPosterization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radial Models.
        /// </summary>
        public static string MenuRadialModels {
            get {
                return ResourceManager.GetString("MenuRadialModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Board.
        /// </summary>
        public static string MenuResetBoard {
            get {
                return ResourceManager.GetString("MenuResetBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Image Position.
        /// </summary>
        public static string MenuResetNodePos {
            get {
                return ResourceManager.GetString("MenuResetNodePos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Image Thresholds.
        /// </summary>
        public static string MenuResetNormalization {
            get {
                return ResourceManager.GetString("MenuResetNormalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Image.
        /// </summary>
        public static string MenuSaveImage {
            get {
                return ResourceManager.GetString("MenuSaveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Video.
        /// </summary>
        public static string MenuSaveVideo {
            get {
                return ResourceManager.GetString("MenuSaveVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square Root.
        /// </summary>
        public static string MenuSquareRoot {
            get {
                return ResourceManager.GetString("MenuSquareRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        public static string MenuStackAverage {
            get {
                return ResourceManager.GetString("MenuStackAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Median.
        /// </summary>
        public static string MenuStackMedian {
            get {
                return ResourceManager.GetString("MenuStackMedian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack Operations.
        /// </summary>
        public static string MenuStackOps {
            get {
                return ResourceManager.GetString("MenuStackOps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        public static string MenuStackSum {
            get {
                return ResourceManager.GetString("MenuStackSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star Masking.
        /// </summary>
        public static string MenuStarMask {
            get {
                return ResourceManager.GetString("MenuStarMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Animation.
        /// </summary>
        public static string MenuStartAnimation {
            get {
                return ResourceManager.GetString("MenuStartAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Animation.
        /// </summary>
        public static string MenuStopAnimation {
            get {
                return ResourceManager.GetString("MenuStopAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structure Extraction.
        /// </summary>
        public static string MenuStructureExtraction {
            get {
                return ResourceManager.GetString("MenuStructureExtraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string MenuView {
            get {
                return ResourceManager.GetString("MenuView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualization Mode.
        /// </summary>
        public static string MenuViewMode {
            get {
                return ResourceManager.GetString("MenuViewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
    }
}
